### ISSUE TITLE
Temporal.io

### ISSUE THREAD

**Issue by piclemx** [ssotax/ssotax#100]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **base_pricing:** Use the vendors cheapest available price suitable for teams/companies. A plan limited to less than 10 users may not be suited for companies.
- **sso_pricing:** Use the vendors cheapest price that includes SSO. 
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **pricing_scheme:** How is the pricing? Is it per user per month? Per month?
- **pricing_sources:** Add a link or a note to where you got the pricing from. One per line.
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
base_pricing: 100
currency: USD
free_sso_providers:
name: Temporal.io
notes: You can add SSO to a Business plan for $200+* per month. * 0-25 is 200$. 26 to 50 is 300$ and 51+ is $500
pricing_scheme: per actions and storage
pricing_sources:
  - https://temporal.io/pricing
  - Quote
scim_pricing: 100
sso_pricing: 5000$ or 700$ as an add-on
updated_at: 2024-11-07
vendor_url: https://temporal.io
```
