### ISSUE TITLE
Add good Vendor: NewRelic

### ISSUE THREAD

**Issue by ewoutvdv** [ssotax/ssotax#104]
```yaml
---
name: New Relic
free_sso_providers:
  - Google
  - Azure AD
  - Any SAML 2.0 implementation
scim_pricing: 418.80
scim_starting_on_plan: Pro plan
sources:
  - https://newrelic.com/pricing
sso_on_free_plans: false
sso_on_all_paid_plans: true
updated_at: 2024-12-03
vendor_url: https://newrelic.com
```
