### ISSUE TITLE
Add Vendor: OpenProject

### ISSUE THREAD

**Issue by samip5** [ssotax/ssotax#110]
They block SSO behind an Enterprise tier despite being open-source.

```yaml
---
base_pricing: 7.25
currency: USD
free_sso_providers:
  - LDAP
name: OpenProject
notes: self-hosted requires yearly sub
pricing_scheme: per user/month
pricing_sources:
  - https://www.openproject.org/pricing/?users=5&currency=usd&mode=onpremises&period=12&support=basic&edition=classic
sso_pricing: 7.25
updated_at: 2024-12-15
vendor_url: https://www.openproject.org/
```
