### ISSUE TITLE
Add Vendor: Beamer

### ISSUE THREAD

**Issue by kimsey0** [ssotax/ssotax#111]
```yaml
---
base_pricing: 59
currency: USD
name: Beamer
pricing_scheme: per month
pricing_sources:
  - https://www.getbeamer.com/pricing
sso_pricing: 299
updated_at: 2024-12-16
vendor_url: https://www.getbeamer.com/
```
