### ISSUE TITLE
Add Mintlify

### ISSUE THREAD

**Issue by kimsey0** [ssotax/ssotax#113]
```yaml
---
base_pricing: 150
currency: USD
name: Mintlify
pricing_scheme: per month
pricing_sources:
  - https://mintlify.com/pricing
sso_pricing: unknown
updated_at: 2025-01-06
vendor_url: https://mintlify.com/
```
