### ISSUE TITLE
Update Vendor: JotForm

### ISSUE THREAD

**Issue by designatedsuccessor** [ssotax/ssotax#116]
```yaml
---
free_sso_providers: None
name: JotForm
updated_at: 2024-01-10
```
