### ISSUE TITLE
Add Vendor: RustDesk

### ISSUE THREAD

**Issue by Alveel** [ssotax/ssotax#119]
```yaml
---
base_pricing: 0
currency: USD
free_sso_providers: []
name: RustDesk
notes: 10 users, additional users for $1 per u/m
pricing_scheme: per user/month
pricing_sources:
  - https://rustdesk.com/pricing/?lang=en
scim_pricing: 19.90
sso_pricing: 19.90
updated_at: 2025-01-17
vendor_url: https://rustdesk.com/
```
