### ISSUE TITLE
Add vendor: Retool

### ISSUE THREAD

**Issue by nicotriballier** [ssotax/ssotax#12]
```yaml
---
base_pricing: 5
currency: USD
free_sso_providers:
  - Google
name: Retool
notes: minimum $60k/y + ~$23.75/end user/month to switch to Enterprise plan that unlocks SSO. Retool also capped their business plan to 25 users forcing essentially every non-startup to go Enterprise
pricing_scheme: fixed cost per year (for Enterprise) + variable cost per end user/month (all plans)
pricing_sources:
  - https://retool.com/pricing
  - Quote
scim_pricing: 60000
sso_pricing: 60000
updated_at: 2023-12-30
vendor_url: https://retool.com
```
