### ISSUE TITLE
Add Vendor: Flourish

### ISSUE THREAD

**Issue by haydenwalker980** [ssotax/ssotax#120]
A data visualisation provider. To even *get* team features it's "call us" pricing.

I may update this in the future if i ever get a quote^^

```yaml
---
base_pricing: ???
currency: USD
free_sso_providers:
  - Google
name: Flourish
notes: SSO starts at "Enterprise" - "call us" pricing for any team features at all
pricing_scheme: per user/month
pricing_sources:
  - https://flourish.studio/pricing/
scim_pricing: ???
sso_pricing: ???
updated_at: 2025-01-17
vendor_url: https://flourish.studio
```

**Comment by haydenwalker980** [comment]
I just got a quote...wow it's bad. Pricing measured on five users.
```yaml
---
base_pricing: 15000
currency: USD
free_sso_providers:
  - Google
name: Flourish
notes: SSO starts at "Enterprise" - "call us" pricing for any team features at all
pricing_scheme: per year
pricing_sources:
  - https://flourish.studio/pricing/
scim_pricing: 20000
sso_pricing: 20000
updated_at: 2025-01-22
vendor_url: https://flourish.studio
```
