### ISSUE TITLE
Add Vendor: sanity.io

### ISSUE THREAD

**Issue by lu3ke** [ssotax/ssotax#123]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **base_pricing:** Use the vendors cheapest available price suitable for teams/companies. A plan limited to less than 10 users may not be suited for companies.
- **sso_pricing:** Use the vendors cheapest price that includes SSO. 
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **pricing_scheme:** How is the pricing? Is it per user per month? Per month?
- **pricing_sources:** Add a link or a note to where you got the pricing from. One per line.
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
base_pricing: 15
currency: USD
free_sso_providers:
  - Github
  - Google
name: Sanity.io
notes: You can add SSO to a plan for $1499/month
pricing_scheme: per user/month
pricing_sources:
  - https://www.sanity.io/pricing
  - https://www.sanity.io/pricing#add-ons
scim_pricing: 1514 minimum (one user plus "SSO add-on")
sso_pricing: 1514 minimum (one user plus "SSO add-on")
updated_at: 2025-02-04
vendor_url: https://www.sanity.io
```
