### ISSUE TITLE
Add Vendor: Cognito Forms

### ISSUE THREAD

**Issue by efgait** [ssotax/ssotax#127]
```yaml
---
base_pricing: Free
currency: USD
name: Cognito Forms
notes: Enterprise plan required for SSO.
pricing_scheme: 20 user/month
pricing_sources:
  - https://www.cognitoforms.com/pricing
  - Public
sso_pricing: 129
updated_at: 2025-02-06
vendor_url: https://www.cognitoforms.com/
```
