### ISSUE TITLE
Add Vendor: OpenObserve

### ISSUE THREAD

**Issue by bcrosnier** [ssotax/ssotax#130]
```yaml
---
base_pricing: 19
currency: USD
free_sso_providers:
  - Google
  - Microsoft
  - GitHub
  - GitLab
name: OpenObserve
notes: ''
pricing_scheme: per month
pricing_sources:
  - https://openobserve.ai/pricing
  - https://openobserve.ai/blog/sso-tax
scim_pricing: ''
sso_pricing: unknown
updated_at: 2025-02-11
vendor_url: https://openobserve.ai/
```

OpenObserve straight up [references ssotax](https://openobserve.ai/blog/sso-tax/), may as well add it.

The free providers (Google, Microsoft, GitHub and GitLab) are provided for, well, free. I put 19 USD as the base price for OpenObserve Cloud Pro, but it could be 0 for OpenObserve Self-hosted (not sure if free pricing should be discarded in this case).   
SAML and OIDC (both cloud and on-premises) are locked behind a "Get in touch" button, presumably linked to an Account Manager in India (if you want to be on the receiving side, [you can apply to the position here](https://openobserve.zohorecruit.com/jobs/Careers/767519000002356001/Technical-Account-Manager)).

OpenObserve has [a blog post defending SSO tax](https://openobserve.ai/blog/sso-tax/) for SAML and OIDC, which claims the Enterprise plan [for both Cloud and self-hosted, including SAML/OIDC] is "free to everyone but large enterprises", but the contents of this blog post are neither on the [pricing page](https://openobserve.ai/pricing), nor the [terms of service](https://openobserve.ai/policies/terms-of-service).

So I'm not sure how it's *really* handled. As of today, [the documentation about SSO](https://openobserve.ai/docs/SSO/) still has TODOs.
