### ISSUE TITLE
Update Vendor: Canva

### ISSUE THREAD

**Issue by mikeroq** [ssotax/ssotax#132]
```yaml
---
base_pricing: 100
currency: USD
free_sso_providers:
  - Apple
  - Facebook
  - Google
  - Microsoft
name: Canva
notes: SSO and SCIM are only available on the Enterprise plan. 25 user minimum required.
pricing_scheme: per user/year
pricing_sources:
  - https://www.canva.com/pricing/
  - Quote
scim_pricing: 300
sso_pricing: 300
updated_at: 2025-02-18
vendor_url: https://www.canva.com/
```

I emailed Canva asking about the enterprise plan. Their response in the email:

> Please note that SSO is only exclusive with our Canva Enterprise Plan (priced at $300/person/year, minimum of 25 members)
