### ISSUE TITLE
Add/Update Vendor: Notion

### ISSUE THREAD

**Issue by alexanderhall-se** [ssotax/ssotax#135]
SSO/SCIM is included in the Business/Enterprise tiers.

```yaml
---
base_pricing: 11.50
currency: USD
free_sso_providers:
  - Apple
  - Google
name: Notion
pricing_scheme: per user/month
pricing_sources:
  - https://www.notion.com/pricing
sso_pricing: 17
updated_at: 2025-02-25
vendor_url: https://www.notion.com
```
