### ISSUE TITLE
Add/Update Vendor: Dropbox

### ISSUE THREAD

**Issue by alexanderhall-se** [ssotax/ssotax#136]
Assuming Business plan as baseline as that's the cheapest plan that allows for more than 1 user.
SSO is available on Business Plus and up.

```yaml
---
base_pricing: 14.50
currency: USD
name: Dropbox
pricing_scheme: per user/month
pricing_sources:
  - https://www.dropbox.com/business/plans-comparison?billing=monthly
sso_pricing: 21.50
updated_at: 2025-02-25
vendor_url: https://www.dropbox.com
```
