### ISSUE TITLE
Add/Update Vendor: Attio

### ISSUE THREAD

**Issue by james-callahan** [ssotax/ssotax#14]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **base_pricing:** Use the vendors cheapest available price suitable for teams/companies. A plan limited to less than 10 users may not be suited for companies.
- **sso_pricing:** Use the vendors cheapest price that includes SSO. 
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **pricing_scheme:** How is the pricing? Is it per user per month? Per month?
- **pricing_sources:** Add a link or a note to where you got the pricing from. One per line.
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
base_pricing: 34
currency: USD
free_sso_providers:
name: Attio
notes:
pricing_scheme: per user/month
pricing_sources:
  - https://attio.com/pricing
  - |
       https://app.attio.com/<org>/settings/security (after logging in and clicking "Upgrade")
scim_pricing: 
sso_pricing: 119
updated_at: 2024-01-17
vendor_url: https://attio.com/
```

![image](https://github.com/ssotax/ssotax/assets/35791147/bc5179e2-598a-4c65-863c-6783b313ad43)
![image](https://github.com/ssotax/ssotax/assets/35791147/19387d79-96cb-4c1b-bf6c-5eb7c0902885)
![image](https://github.com/ssotax/ssotax/assets/35791147/ae165a42-a247-47d7-ba6d-0f15ae5bff76)
