### ISSUE TITLE
Add good Vendor: RepoFlow

### ISSUE THREAD

**Issue by 100tomer** [ssotax/ssotax#140]
**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **scim_starting_on_plan:** When is SCIM available? `lowest` or `highest` 
- **sources:** Add a link or a note to where you got information like pricing from. One per line.
- **sso_on_free_plans:** Is SSO available on free plans?
- **sso_on_all_paid_plans:** Is SSO available on all paid plans? It must be true to appear on this list.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
name: RepoFlow
free_sso_providers:
  - OpenID Connect (any)
  - LDAP
scim_pricing: null
scim_starting_on_plan: null
sources:
  - https://www.repoflow.io/pricing
sso_on_free_plans: true
sso_on_all_paid_plans: true
updated_at: 2025-04-17
vendor_url: https://www.repoflow.io
```
