### ISSUE TITLE
Add Vendor: memtime

### ISSUE THREAD

**Issue by mossytrees** [ssotax/ssotax#143]
```yaml
---
base_pricing: 17
currency: USD
free_sso_providers:
name: memtime
notes: Basic plan @$11/mo says for small teams but doesn't support any project software integrations.  Connect supports integrations teams would need ($17/mo) but you need Premium ($23/mo) or Enteprprise ("contact sales") to add SSO.
pricing_scheme: per user/month with discounts available for 1 or 2 year terms.
pricing_sources:
  - https://www.memtime.com/pricing#price-table
scim_pricing: Requires premoim plan @$23/mo
sso_pricing: requires premium plan @ $23/mo
updated_at: 2025-06-02
vendor_url: https://www.memtime.com/
```
