### ISSUE TITLE
Add Vendor: TheHive

### ISSUE THREAD

**Issue by jjminer** [ssotax/ssotax#147]
```yaml
---
base_pricing: 0
currency: Euro
free_sso_providers:
  - Nope!
name: TheHive (StrangeBee SAS)
notes: On prem.  No information about quantities less than 5 .. or more than 5 for that matter.
pricing_scheme: per 5 user/year
pricing_sources:
  - https://strangebee.com/thehive-pricing-on-prem/
scim_pricing: No Support
sso_pricing: 26,650
updated_at: 2025-06-24
vendor_url: https://strangebee.com/thehive/
```
