### ISSUE TITLE
Add vendor : n8n

### ISSUE THREAD

**Issue by 20-user-20** [ssotax/ssotax#17]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **base_pricing:** Use the vendors cheapest available price suitable for teams/companies. A plan limited to less than 10 users may not be suited for companies.
- **sso_pricing:** Use the vendors cheapest price that includes SSO. 
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **pricing_scheme:** How is the pricing? Is it per user per month? Per month?
- **pricing_sources:** Add a link or a note to where you got the pricing from. One per line.
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
base_pricing: 24
currency: EUR
free_sso_providers:
name: n8n
notes: Only available on the Enterprise plan
pricing_scheme: per user/month
pricing_sources:
  - https://n8n.io/pricing/
  - Quote
scim_pricing: ??
sso_pricing: Only available on the Enterprise plan
updated_at: 2024-02-10
vendor_url: https://n8n.io/
```
