### ISSUE TITLE
We, Augmentt, have released SSO, without a tax :)

### ISSUE THREAD

**Issue by robybrisson** [ssotax/ssotax#18]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Augmentt
- **free_sso_providers:** Microsoft 365
- **scim_pricing:** $199
- **scim_starting_on_plan:** $199
- **sources:** [Add a link or a note to where you got information like pricing from. One per line.
](https://www.augmentt.com/pricing/)
- **sso_on_free_plans:** n/a
- **sso_on_all_paid_plans:** Yes
- **updated_at:** 2024-02-20
- **vendor_url:**https://www.augmentt.com/

```yaml
---
name: Augmentt
free_sso_providers:
  - Microsoft 365
scim_pricing: 199
scim_starting_on_plan: 199
sources:
  - https://www.augmentt.com/pricing/
sso_on_free_plans: n/a
sso_on_all_paid_plans: true
updated_at: 2024-02-20
vendor_url: https://www.augmentt.com/
```
