### ISSUE TITLE
appsmith

### ISSUE THREAD

**Issue by JamesHarrison** [ssotax/ssotax#23]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **base_pricing:** Use the vendors cheapest available price suitable for teams/companies. A plan limited to less than 10 users may not be suited for companies.
- **sso_pricing:** Use the vendors cheapest price that includes SSO. 
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **pricing_scheme:** How is the pricing? Is it per user per month? Per month?
- **pricing_sources:** Add a link or a note to where you got the pricing from. One per line.
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
base_pricing: 60
currency: USD
free_sso_providers:
  - Google
  - GitHub
name: appsmith
notes: Enterprise tier starts around $20,000/yr, plus $20/user/month
pricing_scheme: per user/month
pricing_sources:
  - Quote
scim_pricing: 1667
sso_pricing: 1667
updated_at: 2024-03-20
vendor_url: https://www.appsmith.com/pricing
```
