### ISSUE TITLE
Add GitBook

### ISSUE THREAD

**Issue by elibrody** [ssotax/ssotax#25]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** GitBook
- **base_pricing:** $6 per user allowing Google SSO
- **sso_pricing:** $12 per user plus $82 Monthly platform fee for SAML
- **scim_pricing:** NA
- **pricing_scheme:** Per User Per Month
- **pricing_sources:** [Pricing](https://www.gitbook.com/pricing#compare-plans)
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? Looks like only google in the cheapest plan
- **updated_at:** 2024-03-26
- **vendor_url:** [Gitbook](https://www.gitbook.com)

```yaml
---
base_pricing: 6
currency: USD
free_sso_providers:
  - Google
name: GitBook
pricing_scheme: per user/month
pricing_sources:
  - https://www.gitbook.com/pricing#compare-plans
scim_pricing: NA
sso_pricing: 12 + 82 Platform Fee
updated_at: 2024-03-26
vendor_url: https://www.gitbook.com/
```
