### ISSUE TITLE
 Manatal Add

### ISSUE THREAD

**Issue by sonzanetti** [ssotax/ssotax#27]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Manatal
- **base_pricing:** $15/per user per month.
- **sso_pricing:** $55/per user per month.
- **scim_pricing:** N/A 
- **pricing_scheme:** per user per month.
- **pricing_sources:** https://www.manatal.com/pricing
- **notes:** Manatal only offers SSO in their Enterprise Plus Plan. Furthermore, in the basic plan, they don't even provide 2FA.
- **free_sso_providers:** N/A
- **updated_at:** 2024-04-04
- **vendor_url:** https://www.manatal.com

```yaml
---
base_pricing: 15
currency: USD
free_sso_providers: N/A
name: Manatal
pricing_scheme: per user/month
pricing_sources:
  - https://www.manatal.com/pricing
sso_pricing: 55
updated_at: 2024-04-04
vendor_url: https://www.manatal.com
```
