### ISSUE TITLE
Pomerium adds SSO to any self-hosted application for free

### ISSUE THREAD

**Issue by cmo-pomerium** [ssotax/ssotax#28]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **scim_starting_on_plan:** When is SCIM available? `lowest`` or `highest` 
- **sources:** Add a link or a note to where you got information like pricing from. One per line.
- **sso_on_free_plans:** Is SSO available on free plans?
- **sso_on_all_paid_plans:** Is SSO available on all paid plans? It must be true to appear on this list.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
name: Pomerium
free_sso_providers:
  - Google
  - Apple
  - Github
  - Auth0
  - AzureAD
  - Cognito
  - GitLab
  - OIDC
  - Okta
  - OneLogin
  - Ping
scim_pricing: Free
scim_starting_on_plan: Free
sources:
  - https://www.pomerium.com/pricing/
  - Quote
sso_on_free_plans: true
sso_on_all_paid_plans: true
updated_at: 2024-04-05
vendor_url: https://www.pomerium.com/
```
