### ISSUE TITLE
Add AccessOwl Friends of SSO

### ISSUE THREAD

**Issue by PhilipLR** [ssotax/ssotax#30]
```yaml
---
name: AccessOwl
free_sso_providers:
  - Google
  - Slack
scim_pricing:
scim_starting_on_plan: 
sources:
  - https://www.accessowl.io/pricing
sso_on_free_plans: true
sso_on_all_paid_plans: true
updated_at: 2024-04-11
vendor_url: https://www.accessowl.io/
```
