### ISSUE TITLE
Add Vendor: Plane

### ISSUE THREAD

**Issue by jan--m** [ssotax/ssotax#31]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **base_pricing:** Use the vendors cheapest available price suitable for teams/companies. A plan limited to less than 10 users may not be suited for companies.
- **sso_pricing:** Use the vendors cheapest price that includes SSO. 
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **pricing_scheme:** How is the pricing? Is it per user per month? Per month?
- **pricing_sources:** Add a link or a note to where you got the pricing from. One per line.
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
base_pricing: 0
currency: USD
name: Plane
notes: OSS maintainers refuse to merge community-developed OIDC feature, because they're thinking to charge for SSO.
pricing_scheme: TBD
pricing_sources:
  - https://github.com/makeplane/plane/pull/3341#issuecomment-1887375131
scim_pricing: TBD
sso_pricing: TBD
updated_at: 2024-04-18
vendor_url: https://plane.so
```
