### ISSUE TITLE
Add react-admin

### ISSUE THREAD

**Issue by fzaninotto** [ssotax/ssotax#32]
```yaml
---
name: react-admin
free_sso_providers:
   - Auth0
   - Amplify
   - MSAL
   - CASDoor
   - Directus
   - Firebase
   - Google
   - Keycloack
   - Supabase
scim_pricing:
scim_starting_on_plan:
sources:
  - https://marmelab.com/react-admin/AuthProviderList.html
  - https://react-admin-ee.marmelab.com/#pricing
sso_on_free_plans: true
sso_on_all_paid_plans: true
updated_at: 20024-04-18
vendor_url: https://marmelab.com/react-admin/
```
