### ISSUE TITLE
Add/Update good Vendor: Tailscale

### ISSUE THREAD

**Issue by samlinville** [ssotax/ssotax#34]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **scim_starting_on_plan:** When is SCIM available? `lowest`` or `highest` 
- **sources:** Add a link or a note to where you got information like pricing from. One per line.
- **sso_on_free_plans:** Is SSO available on free plans?
- **sso_on_all_paid_plans:** Is SSO available on all paid plans? It must be true to appear on this list.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
name: Tailscale
free_sso_providers:
  - Google
  - Google Workspace
  - Okta
  - Microsoft Office365
  - Microsoft Entra ID
  - Microsoft Active Directory
  - Microsoft
  - GitHub
  - OneLogin
  - All OIDC compliant identity providers
scim_pricing: 
scim_starting_on_plan: highest
sources:
  - https://tailscale.com/pricing
sso_on_free_plans: true
sso_on_all_paid_plans: true
updated_at: 2024-04-18
vendor_url: https://tailscale.com
```
