### ISSUE TITLE
Update Vendor: Matomo

### ISSUE THREAD

**Issue by jan--m** [ssotax/ssotax#35]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **base_pricing:** Use the vendors cheapest available price suitable for teams/companies. A plan limited to less than 10 users may not be suited for companies.
- **sso_pricing:** Use the vendors cheapest price that includes SSO. 
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **pricing_scheme:** How is the pricing? Is it per user per month? Per month?
- **pricing_sources:** Add a link or a note to where you got the pricing from. One per line.
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
base_pricing: 0
currency: EUR
name: Matomo On-Premise
notes: OSS https://github.com/matomo-org/matomo
pricing_scheme: per year
pricing_sources:
  - https://plugins.matomo.org/LoginOIDC
  - https://plugins.matomo.org/LoginSaml
sso_pricing:
  - OIDC is free
  - SAML costs 499 €
updated_at: 2024-04-19
vendor_url: https://matomo.org
---
base_pricing: 22
currency: EUR
name: Matomo Cloud
notes: Cloud Enterprise is required for SAML/LDAP support.
pricing_scheme: per month
pricing_sources:
  - https://matomo.org/pricing
  - https://matomo.org/matomo-cloud-enterprise/
sso_pricing: unknown
updated_at: 2024-04-19
vendor_url: https://matomo.org
```
