### ISSUE TITLE
Add OVH as a Good Vendor

### ISSUE THREAD

**Issue by signed-log** [ssotax/ssotax#37]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **scim_starting_on_plan:** When is SCIM available? `lowest`` or `highest` 
- **sources:** Add a link or a note to where you got information like pricing from. One per line.
- **sso_on_free_plans:** Is SSO available on free plans?
- **sso_on_all_paid_plans:** Is SSO available on all paid plans? It must be true to appear on this list.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
name: OVHCloud
free_sso_providers:
  - None
scim_pricing: Free
scim_starting_on_plan: lowest
sources:
  - https://corporate.ovhcloud.com/fr/newsroom/news/identity-and-access-management/
  - https://help.ovhcloud.com/csm/world-documentation-account-and-service-management-account-information-users?id=kb_browse_cat&kb_id=7c798fe1551974502d4c6e78b74219bb&kb_category=c2507ca1d89ce114f078b2e82dd3167c
sso_on_free_plans: true
sso_on_all_paid_plans: true
updated_at: 2024-04-21
vendor_url: https://www.ovhcloud.com/fr/
```
