### ISSUE TITLE
Slack supports Google Workspace OAuth (non-SCIM) on any paid plan

### ISSUE THREAD

**Issue by signed-log** [ssotax/ssotax#38]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Use the vendors name 
- **base_pricing:** Use the vendors cheapest available price suitable for teams/companies. A plan limited to less than 10 users may not be suited for companies.
- **sso_pricing:** Use the vendors cheapest price that includes SSO. 
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **pricing_scheme:** How is the pricing? Is it per user per month? Per month?
- **pricing_sources:** Add a link or a note to where you got the pricing from. One per line.
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
base_pricing: 7.25
currency: USD
free_sso_providers:
  - Google
name: Slack
notes: Only Google Workspace OAuth 2.0 is included in any paid plan
pricing_scheme: per user/month
pricing_sources:
  - https://slack.com/help/articles/204078066-Google-Workspace-single-sign-on
  - https://slack.com/help/articles/205168057-Custom-SAML-single-sign-on
  - https://slack.com/pricing
scim_pricing: 12.5
sso_pricing: 7.25
updated_at: 2024-04-2024
vendor_url: https://slack.com
```

Only Google Workspace is supported, not free Google accounts
