### ISSUE TITLE
Add Vendor: Shortcut

### ISSUE THREAD

**Issue by russellpierce** [ssotax/ssotax#4]
*Do you want to add or update the vendor? Adjust the title accordingly!*

```yaml
---
base_pricing: 12
currency: USD
name: Shortcut
pricing_scheme: per user/month
pricing_sources:
  - https://www.shortcut.com/pricing
notes: SSO available as an add-in, but pricing isn't published
sso_pricing: unknown
free_sso_providers:
  - Google
updated_at: 2023-11-02
vendor_url: https://www.shortcut.com
```
