### ISSUE TITLE
Add Vendor: NetBox

### ISSUE THREAD

**Issue by shawniverson** [ssotax/ssotax#40]
```yaml
---
- name: NetBox
- base_pricing: $7,500
- sso_pricing: ?
- scim_pricing: N/A
- pricing_scheme: per year
- pricing_sources:
  - https://netboxlabs.com/pricing/
- notes: The Professional plan for $24,000 does not include SAML, you need to pay extra for it or go to Enterprise. Hopefully someone can provide a quote.
- free_sso_providers:
  - Google
  - Azure
- updated_at: 2024-04-22
- vendor_url: https://netboxlabs.com
```
