### ISSUE TITLE
Add Vendor: WebPT

### ISSUE THREAD

**Issue by loosus** [ssotax/ssotax#44]
```yaml
---
base_pricing: 1900
currency: USD
free_sso_providers:
name: WebPT
notes:
pricing_scheme: Annual
pricing_sources:
  - Quote
scim_pricing: Unknown
sso_pricing: 15,800
updated_at: 2024-05-13
vendor_url: https://webpt.com
```
