### ISSUE TITLE
Add/Update Vendor: Vimeo

### ISSUE THREAD

**Issue by iliketoc0d3aL0T** [ssotax/ssotax#45]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Vimeo, https://vimeo.com/
- **base_pricing:** $10,000 to implement SSO as part of their Enterprise package, regardless of number of users is base price
- **sso_pricing:** Use the vendors cheapest price that includes SSO. 
- **scim_pricing:** Use the vendors cheapest price that includes SCIM. 
- **pricing_scheme:** How is the pricing? Is it per user per month? Per month?
- **pricing_sources:** Add a link or a note to where you got the pricing from. One per line.
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** Do they support free SSO providers like Google, Apple, Github etc.? One per line.
- **updated_at:** yyyy-mm-dd of the day you filed this. 
- **vendor_url:** Use the vendors public website

```yaml
---
base_pricing: $10,000
currency: USD
free_sso_providers:
name: Vimeo
notes: You can add SSO only if you have the Enterprise plan, which starts at $10,000 regardless of number of users
pricing_scheme: flat fee
pricing_sources:
  - email
scim_pricing: $10,000
sso_pricing: $10,000
updated_at: 2024-05-16
vendor_url: https://vimeo.com/
```
