### ISSUE TITLE
Classy

### ISSUE THREAD

**Issue by CbettsRootCap** [ssotax/ssotax#52]
```yaml
---
base_pricing: $830
currency: USD
free_sso_providers:

name: Classy
notes: $3000 base  charge to implement SSO, no MFA supported
pricing_scheme: per user/year
pricing_sources: 
  - Quote
scim_pricing: 
sso_pricing: $1256 
updated_at:  2024-06-13
vendor_url: https://support.classy.org/s/article/federated-sso
```
