### ISSUE TITLE
Add/Update Vendor: Coda

### ISSUE THREAD

**Issue by jean** [ssotax/ssotax#54]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** Coda
- **base_pricing:** $10/month per Doc Maker
- **sso_pricing:**  "Call us" (Enterprise). The previous tier is $30/month, so already a 200% increase. 
- **scim_pricing:**  "Call us" (Enterprise). The previous tier is $30/month, so already a 200% increase.
- **pricing_scheme:** per month per Doc Maker. Editors are free.
- **pricing_sources:** https://coda.io/pricing
- **notes:** --
- **free_sso_providers:** Google, Microsoft
- **updated_at:** 2024-06-19 
- **vendor_url:** https://coda.io/

```yaml
---
base_pricing: 10
currency: USD
free_sso_providers:
  - Microsoft
  - Google
name: Coda
notes: "Call us" (Enterprise) for both SAML and SCIM. The previous tier is $30/month, so already a 200% increase.
pricing_scheme: per month per Doc Maker. Editors are free.
pricing_sources:
  - https://example.com/pricing
scim_pricing: 
sso_pricing: 
updated_at: 2024-06-19
vendor_url: https://coda.io/
```
