### ISSUE TITLE
Add FileFlows

### ISSUE THREAD

**Issue by sahmeepee** [ssotax/ssotax#55]
```yaml
---
base_pricing: 20
currency: USD
free_sso_providers:
  - OpenID Connect
name: FileFlows
notes: n/a
pricing_scheme: per month
pricing_sources:
  - https://fileflows.com/pricing
scim_pricing: n/a
sso_pricing: 100
updated_at: 2024-07-14
vendor_url: https://fileflows.com/
```
