### ISSUE TITLE
Add Mailslurp

### ISSUE THREAD

**Issue by nikeshashar** [ssotax/ssotax#56]
**How to use? Fill the yaml file below!**
- **name:** Mailslurp
- **base_pricing:** $0.00
- **sso_pricing:** $1021 
- **scim_pricing:** N/A
- **pricing_scheme:** Per user per month
- **pricing_sources:** https://www.mailslurp.com/pricing/
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** No
- **updated_at:** 2024-07-15
- **vendor_url:** [Use the vendors public website](https://www.mailslurp.com/)

```yaml
---
base_pricing: 0.00
currency: USD
free_sso_providers:
name: Mailslurp
notes: Enterprise plan only at $1021 per month
pricing_scheme: per user/month
pricing_sources:
  - https://www.mailslurp.com/
scim_pricing: 
sso_pricing: 1021
updated_at: 2024-07-15
vendor_url: https://www.mailslurp.com/
```
