### ISSUE TITLE
Update Hex

### ISSUE THREAD

**Issue by thecjharries** [ssotax/ssotax#58]
```yaml
---
base_pricing: 36
currency: USD
free_sso_providers:
name: Hex
notes: 
pricing_scheme: per user/month
pricing_sources:
  - https://hex.tech/pricing/
  - Quote
scim_pricing: 150
sso_pricing: 150
updated_at: 2024-07-18
vendor_url: https://hex.tech/
```
