### ISSUE TITLE
Add DocuSeal

### ISSUE THREAD

**Issue by merced317** [ssotax/ssotax#6]
*Do you want to add or update the vendor? Adjust the title accordingly!*

**How to use? Fill the yaml file below!**
- **name:** DocuSeal
- **base_pricing:** Free
- **sso_pricing:** $20/user
- **scim_pricing:** $20/user
- **pricing_scheme:** Per month
- **pricing_sources:** https://www.docuseal.co/pricing
- **notes:** If you need to clarify pricing, please add a note.
- **free_sso_providers:** No
- **updated_at:** 2023-11-15
- **vendor_url:** [Use the vendors public website](https://www.docuseal.co/)

```yaml
---
base_pricing: Free
currency: USD
free_sso_providers:
name: DocuSeal
notes: You can add SSO to a plan for $20 per u/m.
pricing_scheme: per user/month
pricing_sources:
  - https://www.docuseal.co/pricing
scim_pricing:
sso_pricing: 20
updated_at: 2023-11-15
vendor_url: https://www.docuseal.co/
```
