### ISSUE TITLE
Add: OneSignal

### ISSUE THREAD

**Issue by CounterClops** [ssotax/ssotax#61]
The sso_pricing is based off the yearly minimum spend divided by 12 to get the cost per month for SSO

```yaml
---
base_pricing: 9
currency: USD
name: OneSignal
notes: You get SSO in the Enterprise plan, which requires a $8000 per annum minimum spend. Advised by their sales team
pricing_scheme: per month
pricing_sources:
  - https://onesignal.com/pricing
  - Quote
sso_pricing: 666.66
updated_at: 2024-08-13
vendor_url: https://onesignal.com
```
