### ISSUE TITLE
Add Xero

### ISSUE THREAD

**Issue by joelkino** [ssotax/ssotax#65]
```yaml
---
base_pricing: 35
currency: AUD
free_sso_providers:
  - Xero
name: No SSO Integrations Available
notes: Xero does not integrate with any 3rd party IDPs
pricing_scheme: N/A
pricing_sources:
  - https://www.xero.com/au/pricing-plans/
  - Quote
scim_pricing: 60
sso_pricing: N/A
updated_at: 2024-09-06
vendor_url: https://www.xero.com/au/pricing-plans/
```
