### ISSUE TITLE
Rocket.chat now has SSO in their free plan

### ISSUE THREAD

**Issue by Alveel** [ssotax/ssotax#67]
```yaml
---
name: Rocket.Chat
free_sso_providers:
  - Google
  - Facebook
  - GitLab
  - Github
  - LinkedIn
  - Nextcloud
  - WordPress
  - MS Office 365
  - Keycloak
  - Okta
  - Custom
scim_pricing: ??
scim_starting_on_plan: ??
sources:
  - https://www.rocket.chat/pricing
sso_on_free_plans: true
sso_on_all_paid_plans: true
updated_at: 2024-09-09
vendor_url: https://www.rocket.chat/
```
