### ISSUE TITLE
Add good Vendor: KnowBe4

### ISSUE THREAD

**Issue by brynmoorhouse** [ssotax/ssotax#71]
```yaml
---
name: KnowBe4
free_sso_providers:
  - Any SAML
scim_pricing: $0.90
scim_starting_on_plan: lowest
sources:
  - https://www.knowbe4.com/pricing-security-awareness-training
sso_on_free_plans: N/A
sso_on_all_paid_plans: true
updated_at: 2024-09-13
vendor_url: https://www.knowbe4.com
```
