### ISSUE TITLE
Update Vendor: RingCentral

### ISSUE THREAD

**Issue by brynmoorhouse** [ssotax/ssotax#75]
No Longer Bad! SSO offered on lowest priced plan. 

Good YAML

```yaml
---
name: RingCentral
sources:
  - https://www.ringcentral.com/office/plansandpricing.html
sso_on_free_plans: false
sso_on_all_paid_plans: true
updated_at: 2024-09-19
vendor_url: https://www.ringcentral.com
```
