### ISSUE TITLE
Update Vendor: Intercom

### ISSUE THREAD

**Issue by brynmoorhouse** [ssotax/ssotax#76]
Pricing Update

```yaml
---
base_pricing: 29
currency: USD
name: Intercom
notes: Pricing based on billed yearly pricing
pricing_scheme: per seat/month
pricing_sources:
  - https://intercom.com/pricing
sso_pricing: 132
scim_pricing: 132
updated_at: 2024-09-19
vendor_url: https://intercom.com
```
