### ISSUE TITLE
Update Vendor: Bitrise

### ISSUE THREAD

**Issue by brynmoorhouse** [ssotax/ssotax#77]
Pricing Update only

```yaml
---
base_pricing: 89
currency: USD
name: Bitrise
pricing_scheme: per user/month
pricing_sources:
  - https://www.bitrise.io/plans-pricing
sso_pricing: 202.50
updated_at: 2024-09-19
vendor_url: https://www.bitrise.io
```
