### ISSUE TITLE
Update Vendor: Mattermost

### ISSUE THREAD

**Issue by brynmoorhouse** [ssotax/ssotax#78]
All paid plans now include SSO: https://mattermost.com/pricing/

Good YAML

```yaml
---
name: Mattermost
scim_pricing: 10
scim_starting_on_plan: lowest
sources:
  - https://mattermost.com/pricing/
sso_on_free_plans: false
sso_on_all_paid_plans: true
updated_at: 2024-09-19
vendor_url: https://mattermost.com/
```
