### ISSUE TITLE
Add/Update Vendor: [Minio]

### ISSUE THREAD

**Issue by MegaShinySnivy** [ssotax/ssotax#80]
Update Minio mentioning purposefully bad OIDC support

```yaml
---
base_pricing: 0
currency: USD
free_sso_providers:
  - Any OIDC compatible
name: Minio
notes: Minio purposefully kneecaps their SSO support by making it so if the server does not detect the provider at startup, it will not expose that provider for logon unless you restart the service, leading to downtime. A PR was provided to fix this, but was only permitted for use in their enterprise offering. See the following for more details. https://github.com/minio/minio/pull/20333#pullrequestreview-2308500694
pricing_scheme: per TB/Month
pricing_sources:
  - https://min.io/pricing
scim_pricing: 0
sso_pricing: 0
updated_at: 2024_09_22
vendor_url: https://min.io/
```
