### ISSUE TITLE
Add Vendor: SonarCloud

### ISSUE THREAD

**Issue by Bouke** [ssotax/ssotax#81]
```yaml
---
base_pricing: 30
currency: EUR
free_sso_providers:
name: SonarCloud
notes: "contact sales" for Enterprise/sso pricing
pricing_scheme: per month
pricing_sources:
  - https://www.sonarsource.com/plans-and-pricing/sonarcloud/
scim_pricing: ???
sso_pricing: ???
updated_at: 2024-09-23
vendor_url: https://www.sonarsource.com/
```
