### ISSUE TITLE
Add good vendor: ToolJet

### ISSUE THREAD

**Issue by haydenwalker980** [ssotax/ssotax#82]
```yaml
---
name: ToolJet
free_sso_providers:
  - Google
  - GitHub
scim_pricing: 107
scim_starting_on_plan: highest
sources:
  - https://www.tooljet.com/pricing
sso_on_free_plans: false
sso_on_all_paid_plans: true
updated_at: 2024-09-24
vendor_url: https://tooljet.com
```
