### ISSUE TITLE
Add vendor: Slido

### ISSUE THREAD

**Issue by haydenwalker980** [ssotax/ssotax#83]
```yaml
---
base_pricing: 210
currency: USD
free_sso_providers:
  - Google
  - Webex
name: Slido
notes:
pricing_scheme: per year
pricing_sources:
  - https://www.slido.com/pricing?plan=annual
scim_pricing: 2400
sso_pricing: 2400
updated_at: 2024-09-26
vendor_url: https://slido.com
```
