### ISSUE TITLE
Add/Update Vendor: Canny

### ISSUE THREAD

**Issue by haydenwalker980** [ssotax/ssotax#92]
This one's a bit complicated, I understand if you don't OK this.

```yaml
---
base_pricing: 99
currency: USD
free_sso_providers:
  - Facebook
  - GitHub
  - Google
name: Canny
notes: the SSO they list as free is only for authenticating standard users. for admin users SSO is apart of their Business plan which has "call us" pricing
pricing_scheme: per month
pricing_sources:
  - https://canny.io/pricing
  - https://help.canny.io/en/collections/2445416-authentication-tools
  - 
scim_pricing: ???
sso_pricing: ???
updated_at: 2024-11-01
vendor_url: https://canny.io
```
