### ISSUE TITLE
Add hoppscotch.io to bad

### ISSUE THREAD

**Issue by tgmatt** [ssotax/ssotax#95]
```yaml
---
base_pricing: Free
currency: USD
free_sso_providers:
- Google
- Microsoft
- GitHub
name: Hoppscotch
notes: N/A
pricing_scheme: per user/month
pricing_sources:
  - https://docs.hoppscotch.io/documentation/self-host/getting-started
scim_pricing: N/A
sso_pricing: 19
updated_at: 2024-11-04
vendor_url: https://hoppscotch.io
```
