### ISSUE TITLE
Chromatic

### ISSUE THREAD

**Issue by kimsey0** [ssotax/ssotax#97]
```yaml
---
name: Chromatic
base_pricing: 149
currency: USD
pricing_scheme: per month
pricing_sources:
  - https://www.chromatic.com/pricing
sso_pricing: unknown
updated_at: 2024-11-06
vendor_url: https://www.chromatic.com
```
